# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches:
      - master
      - feature/* 
      - features/*
      - develop
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: set version
        run: npm version 1.9.9-dev-$VERSION --no-git-tag-version
        env:
          VERSION: ${{ github.run_number }}
      - name: prepare
        run: npm install
      - name: build
        run: npm run package
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-ext-${{ github.run_number }}
          path: "*.vsix"
